### PR TITLE
Add Luna

### PR DESCRIPTION
**Pull request by mattjw79**

### CODE REVIEW

**Review by Cperez2187 — APPROVED** [review]
Welcome Matt and that sweet girl Luna

**Review by samwhale — APPROVED** [review]
Love the description

**Comment by Burnett2k** [comment]
looks good!

**Review by Burnett2k — APPROVED** [review]

**Comment by ryan-roemer** [comment]
It looks like we did **not** get a real release on this PR and should have. From the logs:

```
Add Luna
[4:43:07 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[4:43:07 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Add Luna
[4:43:07 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[4:43:07 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 2 commits complete: no release
[4:43:07 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[4:43:07 PM] [semantic-release] › ℹ  There are no relevant changes, so no new version is released
```

I'm guessing that @mattjw79 skipped the husky checks demanding commitlint-friendly commit messages (I tend to normally do this my personal development and then check later when I'm ready for PR). I think this is a good time to reconsider: https://github.com/FormidableLabs/dogs/issues/24 which says "run commitlint in CI" and optionally not even bothering in husky/local since my personal workflow at least has a bias against precommit hooks and in particular commit message ones.

Thoughts @mattjw79 @iandvt @carbonrobot ?

**Pull request merged**
